### ISSUE TITLE
Kernel panic and broken screen

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#4] opened 2018-12-06 12:05 UTC
hello, I did such steps that you described but got

![unadjustednonraw_thumb_30fd](https://user-images.githubusercontent.com/738921/49583109-31125480-f968-11e8-9aff-31602a240bb9.jpg)

can it happens because I have extra 8gb of memory instead of default 2gb?

I tried to co copy EFI from your repo and did in console

`sudo "/Applications/Install macOS High Sierra.app/Contents/Resources/createinstallmedia" --volume  /Volumes/install_osx --nointeraction`

after that I got such

<img width="870" alt="monosnap 2018-12-06 15-13-52" src="https://user-images.githubusercontent.com/738921/49583526-8e5ad580-f969-11e8-9b4c-870b798cb85b.png">

**Comment by rafaelmaeuer** [comment] 2018-12-06 15:13
Hi @idoo it is important that you use UniBeast v8.1.0 and I mean this specific version. Otherwise I wasn't able to create a working install media.

**Comment by idoo** [comment] 2018-12-06 15:48
i did it with uniboot from your repo, but result is same, maybe because i
use mojavie to install it ¯\_(ツ)_/¯

may be you have a usb drive or image of disk that you used for boot? in
this case I can use it to check

**Comment by rafaelmaeuer** [comment] 2018-12-06 15:55
I forgot to mention, I use 8GB of extra RAM too so this wont be the issue. I guess the problem is Mojave then. Maybe you need to try the newest unibeast version for that. Tell me if you have success!

**Comment by idoo** [comment] 2018-12-06 17:52
@rafaelmaeuer I tried uniboot from your repo and latest one, got same result :(

Also tried different versions of clover :(

**Comment by idoo** [comment] 2018-12-10 11:30
Spent weekends to get it run, no change ¯\_(ツ)_/¯ Even El Capitan doesn't boot :(

@rafaelmaeuer could you please try to create a USB drive based on this steps, is it bootable?

Also could you please post BIOS configuration, please?

**Comment by idoo** [comment] 2018-12-10 12:17
looks like correct one is 

```
advanced-> VT-d [disabled].
advanced-> USB Configuration -> Legacy USB [auto], XHCI pre-boot [enabled]
```

for install should be disabled, than usb3 support 
`XHCI Pre – Boot Mode = Enabled`

**Comment by rafaelmaeuer** [comment] 2018-12-10 22:24
Hi, @idoo,

I will try to create a working boot stick.
My Bios is version 214 with following settings:

```
Intel Virtualization Technology [Enabled]
Intel AES-NI [Enabled]
VT-d [Enabled]

SATA Mode Selection [AHCI]

DVMT Pre-Allocated [64M]

Intel(R) Anti-Theft Technology [Enabled]

Legacy USB Support [Enabled]
XHCI Pre-Boot Mode [Disabled]

Network Stack [Disabled]
```

**Comment by idoo** [comment] 2018-12-11 05:10
hm, have exactly the same ¯\_(ツ)_/¯

**Comment by idoo** [comment] 2018-12-11 05:11
@rafaelmaeuer I'll cross my fingers and will wait for that USB :)

As I got, something wrong with `DSDT.aml` and `SSDT.aml` files from this repo, they are doesn't works on latest Hight Sierra

**Comment by idoo** [comment] 2018-12-13 06:49
@rafaelmaeuer any luck?

**Comment by rafaelmaeuer** [comment] 2018-12-13 18:28
Hey @idoo,

I was able to create a bootable USB-drive for Mojave.
Therefore I updated all kexts and the readme should now contain the correct information about how to rebuild it. Im currently figuring out how to get Mojave booting 😄 

Good luck.

Proof:
![img_4556](https://user-images.githubusercontent.com/6418459/49959195-2c701200-ff0d-11e8-9edb-6dcc44c27b30.JPG)

**Comment by idoo** [comment] 2018-12-13 18:31
@rafaelmaeuer could you please make a copy of your USB and share it with me somehow?)

**Comment by idoo** [comment] 2018-12-13 18:32
btw, what is your WIFI card? Looks like default one would not work mac, right?

**Comment by rafaelmaeuer** [comment] 2018-12-13 18:34
The USB is about 8GB, please follow the readme and try to build it on your own.
Yes WiFi card is replaced by Broadcom BCM4352, I will add the information to the readme.

**Comment by idoo** [comment] 2018-12-13 18:35
and do you know, how I can generate 

DSDT.aml & SSDT.aml ?

Looks that some problem when I'm using that files

http://bit.ly/2QtM9F7

is that one good?

**Comment by rafaelmaeuer** [comment] 2018-12-13 18:38
The generation of SSDT is covered by the readme: [Link](https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh#ssdt). DSDT is not, because the one in the repo works quite perfect for me. For DSDT patching have a look at this repo: [Link](https://github.com/danieleds/Asus-UX32VD-Hackintosh/tree/master/src/DSDT)

**Comment by rafaelmaeuer** [comment] 2018-12-13 18:41
> and do you know, how I can generate
> 
> DSDT.aml & SSDT.aml ?
> 
> Looks that some problem when I'm using that files
> 
> https://aliexpress.com/item/AzureWave-AW-CE123H-BCM4352-BCM94352HMB-Half-Mini-PCIe-PCI-express-802-11AC-867Mbps-Wireless-WIFI-WLAN/32452403101.html
> 
> is that one good?

looks fine, think about the need of cable-adapters when switching to another card: [Link](http://forum.notebookreview.com/threads/upgrading-asus-ux32vd-wireless-card-antenna-connector-problem-help.731735/)

**Comment by idoo** [comment] 2018-12-13 18:49
ah, I saw it, are you sure that UX32VD contains `SandyBridge` ?

https://www.asus.com/Laptops/ASUS-ZenBook-UX32VD/specifications/

https://ark.intel.com/products/65707/Intel-Core-i5-3317U-Processor-3M-Cache-up-to-2-60-GHz-

Looks like `Products formerly Ivy Bridge`

and from docs

`1 = Ivy Bridge` from ssdtPRGen.sh

**Comment by idoo** [comment] 2018-12-13 19:02
looks fine, think about the need of cable-adapters when switching to another card: Link

why do I need it? looks connectors are same

that one I have now:

![unadjustednonraw_thumb_13](https://user-images.githubusercontent.com/738921/49961059-c0000d80-ff22-11e8-8a7d-44e573ee91c9.jpg)

**Comment by rafaelmaeuer** [comment] 2018-12-13 19:14
looks same but is different believe me, have a look at this [blog entry](http://forum.notebookreview.com/threads/upgrading-asus-ux32vd-wireless-card-antenna-connector-problem-help.731735/)

**Comment by rafaelmaeuer** [comment] 2018-12-13 19:16
> ah, I saw it, are you sure that UX32VD contains `SandyBridge` ?
> 
> https://www.asus.com/Laptops/ASUS-ZenBook-UX32VD/specifications/
> 
> https://ark.intel.com/products/65707/Intel-Core-i5-3317U-Processor-3M-Cache-up-to-2-60-GHz-
> 
> Looks like `Products formerly Ivy Bridge`
> 
> and from docs
> 
> `1 = Ivy Bridge` from ssdtPRGen.sh

Yes you are right, it is ivy bridge

**Comment by idoo** [comment] 2018-12-13 20:19
is that one good? http://bit.ly/2S3HNSc
only connector different? so, I can use a blowtorch :)

**Comment by rafaelmaeuer** [comment] 2018-12-13 20:24
it looks familiar to what I used, why using a blowtorch? I just plugged the adapters in between.

**Comment by idoo** [comment] 2018-12-13 20:31
hmm, do you know any cards with Bluetooth 5,0 or at least wifi a/c compatible with mac and that asus?
as I understood, I need kext anyway for patching, right?

does your Bluetooth/Airdrop work well?

**Comment by rafaelmaeuer** [comment] 2018-12-13 21:00
sorry I didn't investigated about BT 5.0 cards. Yes the Broadcom card needs 2 kexts to run Wifi, and 2 for BT. Im very happy with it, it supports a/c and I'm using it in my other Hackintosh as well with apple Mouse and Keyboard - without problems. I don't use airdrop much so cant tell about that.

**Comment by idoo** [comment] 2018-12-14 10:46
did you get Mojave install work?

**Comment by rafaelmaeuer** [comment] 2018-12-14 10:48
> did you get Mojave install work?

check!
![img_4559](https://user-images.githubusercontent.com/6418459/49999042-18242780-ff96-11e8-822f-eabf80982969.JPG)

**Comment by idoo** [comment] 2018-12-14 10:48
looks sexy!
On Wednesday I'll come back home and will try to install it!

Btw, please do not clear your USB drive, ok?)

**Comment by idoo** [comment] 2018-12-18 16:50
@rafaelmaeuer I'm having `The disk could not be created because of an error: An error occured: -1728. Finder got an error: Can’t get disk "Install macOS Mojave".`
when I use disc creator tool 

maybe you could create a copy of your USB and share it somehow?

**Comment by idoo** [comment] 2018-12-18 19:48
Finally, I did startup disk with `Install Disk Creator` but have such problem 

any ideas?

![unadjustednonraw_thumb_3155](https://user-images.githubusercontent.com/738921/50179013-0c7a8d00-0317-11e9-90ed-0370bb20534d.jpg)

**Comment by rafaelmaeuer** [comment] 2018-12-18 19:59
I experienced some graphic glitches sometimes too, but it looks different from what you got. In my case it helps to close the lid, wait for some seconds (best is until going into sleep mode) then waking up by pressing power-button and then arrow-up key to get display showing up again. Maybe try this.

**Comment by idoo** [comment] 2018-12-19 05:15
Finally I installed it (created PR)

![unadjustednonraw_mini_3159](https://user-images.githubusercontent.com/738921/50200234-095abd80-0366-11e9-8195-24b26a745c9b.jpg)
sometimes (often) I have such issue

that keep on screen after restart for few minutes, so looks something completely wrong and it could damage screen

![unadjustednonraw_thumb_3158](https://user-images.githubusercontent.com/738921/50200249-27c0b900-0366-11e9-9c35-4a84e6f3efb6.jpg)

**Comment by rafaelmaeuer** [comment] 2018-12-19 10:28
Congrats first, I see you added a lot of tickets. The grafics glitch doesn't occur that often at mine and also only on os x booting, never after reboot...

**Comment by idoo** [comment] 2018-12-19 10:59
I happens on each 2nd/3rd boot, so anyway would be nice to find a reason of this

**Comment by rafaelmaeuer** [comment] 2018-12-19 12:46
I had the issue just at my last reboot. Just closing the lid shortly and reopening followed by pressing arrow-up resulted in correct grafics displayed again.

**Comment by idoo** [comment] 2018-12-23 19:09
Looks like it's our case
https://www.tonymacx86.com/threads/solved-black-screen-after-upgrade-to-high-sierra.237050/page-10

**Comment by idoo** [comment] 2018-12-23 20:57
Tested — doesn't solved it

https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/

another option

**Comment by idoo** [comment] 2018-12-24 11:50
asked for help here https://www.tonymacx86.com/threads/asus-ux32vd-graphics-crashed.268035/#post-1877976

**Comment by rafaelmaeuer** [comment] 2018-12-25 22:03
can you avoid writing my clear name in blogs please ([link](https://www.tonymacx86.com/threads/asus-ux32vd-graphics-crashed.268035/#post-1878003)). Maybe write repository owner? Display issue should go to a new topic btw.

**Comment by idoo** [comment] 2018-12-26 10:22
sorry, removed it!

**Comment by idoo** [comment] 2018-12-26 12:31
what do you think, maybe we should use such patch?
https://olarila.com/forum/viewtopic.php?t=3111

**Comment by rafaelmaeuer** [comment] 2018-12-26 22:55
what is it good for?

**Comment by idoo** [comment] 2018-12-26 22:57
I tried — it doesn't solve the issue

I thought t could be related to `Framebuffer`, but more looks like some memory patch goes wrong

**Comment by idoo** [comment] 2018-12-26 23:35
What do you think, could it be related to our differences in hardware? I have i5 core and maybe I should create my own version of DSDT ?

**Comment by rafaelmaeuer** [comment] 2018-12-27 14:28
I'm not sure, but creating your own DSDT might be a good idea, it could solve some of your problems. If you are able to do it, please document your steps for the DSDT section in the readme!

**Comment by rafaelmaeuer** [comment] 2020-07-01 20:37
DSDT creation is now part of the readme!

**Closed as completed by rafaelmaeuer** 2020-07-01 20:37 UTC

**Comment by ganz-clang** [comment] 2020-12-12 21:43
Hello, guys

Thnx for the nice topic

Did you find a way to get rid of graphics glitches ?

Also is Scale the Screen works correct for you?

**Comment by idoo** [comment] 2020-12-14 11:23
@ganz-clang nope, as I remember it still works with glitches

regarding scale — I think it works well

**Comment by rafaelmaeuer** [comment] 2020-12-17 13:42
I didn't use this laptop frequently in the last time, so I can't tell much about glitches. What do you mean by scale, do you target fullHD resolution or retina scaling?

**Comment by ganz-clang** [comment] 2020-12-19 22:12
I have had the black screen was trying to change screen resolution to 1600x900
now i've built OpenCore Based setup and this issue has gone

graphics glitches on boot/reboot are still in place

**Comment by ganz-clang** [comment] 2020-12-23 17:53
> graphics glitches on boot/reboot are still in place

the issue is gone in case hdmi external display is on at boot/reboot

**Comment by ganz-clang** [comment] 2020-12-23 17:56
another issue is AppleALC layout-id for ALC269VB
did you found that magic number at all?

**Comment by rafaelmaeuer** [comment] 2020-12-24 23:48
My laptop has the fullHD display, working on full resolution with clover...
What do you need the ALC magic number for?
Could you share your OpenCore setup?

**Comment by ganz-clang** [comment] 2020-12-29 07:55
>What do you need the ALC magic number for?

in order to get rid of VoodooHDA of course

**Comment by rafaelmaeuer** [comment] 2020-12-29 14:13
You can use AppleALC, it is working. VoodooHDA is just an optional alternative.

**Comment by ganz-clang** [comment] 2020-12-29 23:14
nope. I  can't ...
did you know the correct layout-id for ALC269VB codec for ASUS UX32VD ?

I've tested all of them with no luck
https://github.com/acidanthera/AppleALC/tree/master/Resources/ALC269

thnx.

**Comment by rafaelmaeuer** [comment] 2020-12-31 12:41
Sorry I just use AppleALC.kext and the sound is working... 
If the problem persists fell free to open a new issue.
